CREATE DATABASE GERENCIARFUNCIONARIOS;
USE GERENCIARFUNCIONARIOS;

CREATE TABLE FUNCIONARIO (
ID INT PRIMARY KEY NOT NULL,
NOME VARCHAR(64) NOT NULL,
CPF VARCHAR(11) NOT NULL,
IDADE INT NOT NULL,
ENDERECO VARCHAR(120) NOT NULL,
EMAIL VARCHAR(120) NOT NULL,
CARGO VARCHAR(64) NOT NULL,
SALARIO DECIMAL(8,2) NOT NULL,
DATA_CONTRATACAO DATE NOT NULL,
SITUACAO VARCHAR(10) NOT NULL
)

CREATE TABLE MESSAGE (
ID INT PRIMARY KEY NOT NULL,
TEXT VARCHAR(120) NOT NULL,
DATA DATETIME NOT NULL
)
